Notes Jun-11, 2014
========================================================

This is a notes document where I'll be scribing thoughts while working on this dataset.

Today I'm just setting up the environment and becoming familiar with what is in the dataset and making initial predictions on how to approach the data.

Starting to look at the data using str(dTrain). The immediate variables that stick out to me are...

* number_of_downvotes_of_request_at_retrieval: High downvotes, less likely
* number_of_upvotes_of_request_at_retrieval: High upvotes, more likely
* post_was_edited: Edits to add in "thanks!" or to cover up a controversial statement?
* request_number_of_comments_at_retrieval: More comments, more controversy?
* request_text: Parse for keywords on successful requests vs unsuccessful requests
* request_text_edit_aware: What was edited in/out?
* request_title: Keywords
* requester_account_age_in_days_at_request
* requester_days_since_first_post_on_raop_at_request: Multiple posts (!=0) indicates greater success?
* requester_number_of_comments_at_request: More comments, better odds
* requester_number_of_posts_at_request: More posts, better odds
* requester_received_pizza: The final result
* requester_subreddits_at_request: If drug subreddits (opiates) then bad. If happy subreddits (secretsanta) then good.
* requester_upvotes_minus_downvotes_at_request: Indicates activity and favorability of account by reddit community
* requester_upvotes_plus_downvotes_at_request: Indicates activity by reddit community
* requester_user_flair: Secret Santa flair and other flair is very good
* requester_username: Nondictionary words or usernames with numbers at the end probably bad? Wouldn't give pizza to xXEmOGiRL420Xx

So lots of variables stick out. By intuitions, the most important variables to start with I think are account age, account activity, account karma, account flair, and the net upvote score of the post. I'll probably start at net upvote score since it's easy to work with. That leaves my starting variable palette with:

Account age: requester_account_age_in_days_at_request
Account activity: requester_number_of_posts_at_request, requester_number_of_comments_at_request, requester_upvotes_plus_downvotes_at_request 
Account karma: requester_upvotes_minus_downvotes_at_request
Account flair: requester_user_flair
Net upvote score of post: number_of_upvotes_of_request_at_retrieval, number_of_downvotes_of_request_at_retrieval
Received pizza?: requester_received_pizza 

For a user account, are comments more or less important than posts?

Going to look at the proportion of people who get pizza to begin with.

* TRUE 994, FALSE 3046

So, ~25% of people get pizza while ~75% of people do not.

For giggles, I'm going to submit a dataset where nobody gets pizza.

```{r}
submit <- data.frame(request_id = dTest$request_id, requester_received_pizza = 0)
```

My submission put me as tied for dead last place with a score of 0.500. I'm surprised, I thought the number would be much closer to 75%. I'm going to have to be much more clever.